<?php

declare(strict_types=1);

namespace RoundlyConsulting\Money\Currencies;

use RoundlyConsulting\Money\Currency;
use RoundlyConsulting\Money\Exceptions\InvalidMoneyConfiguration;

/**
 * The bundled ISO 4217 list (resources/data/iso4217.php, generated by
 * bin/generate-iso4217.php from SIX List One + CLDR `en` symbols).
 */
final class IsoCurrencyData
{
    /** @return list<Currency> */
    public static function load(): array
    {
        $rows = require dirname(__DIR__, 2).'/resources/data/iso4217.php';

        if (! is_array($rows)) {
            throw InvalidMoneyConfiguration::invalid('resources/data/iso4217.php', 'the data file must return a list of rows');
        }

        $currencies = [];

        foreach ($rows as $row) {
            $currencies[] = self::currency($row);
        }

        return $currencies;
    }

    private static function currency(mixed $row): Currency
    {
        if (! is_array($row)
            || ! is_string($row[0] ?? null)
            || ! is_int($row[1] ?? null)
            || ! is_int($row[2] ?? null)
            || ! is_string($row[3] ?? null)
            || ! (is_string($row[4] ?? null) || ($row[4] ?? null) === null)) {
            throw InvalidMoneyConfiguration::invalid('resources/data/iso4217.php', 'every row must be [code, numeric, exponent, name, symbol]');
        }

        return new Currency($row[0], $row[2], $row[3], $row[4], $row[1], iso: true);
    }
}
